In [1]:
L1 = [1, 2, 3]
L2 = [1, 4, 9]

In [2]:
L1+L2

[1, 2, 3, 1, 4, 9]

In [3]:
res = []
for i,j in zip(L1,L2):
    res.append(i+j)

In [4]:
res

[2, 6, 12]

In [5]:
res= []
for i in range(len(L1)):
    res.append(L1[i]+L2[i])
    

In [6]:
res

[2, 6, 12]

In [7]:
import numpy

In [8]:
L1 = numpy.array(L1)
L2 = numpy.array(L2)

In [9]:
L1+L2

array([ 2,  6, 12])

In [10]:
import numpy as np

In [11]:
import numpy as havij

In [12]:
L1 = np.array(L1)
L2 = np.array(L2)

In [15]:
L1+L2

array([ 2,  6, 12])

In [14]:
L1 = havij.array(L1)
L2 = havij.array(L2)

In [16]:
L1+L2

array([ 2,  6, 12])

In [25]:
import math
def myfunc(x):
    res = []
    for i in range(x):
        res.append(math.sqrt(i**2+i**3+i**4))
    return res

In [27]:
%timeit myfunc(1000000)

1.46 s ± 38.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [28]:
def myfunc(x):
    res = np.arange(x)
    res = np.sqrt(res**2+res**3+res**4)
    return res

In [29]:
%timeit myfunc(1000000)

<ipython-input-28-31745a1883e2>:3: RuntimeWarning: invalid value encountered in sqrt
  res = np.sqrt(res**2+res**3+res**4)


23.2 ms ± 288 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Learning

In [31]:
import numpy as np

In [32]:
L1 = [1,2,1000]

In [33]:
np.array(L1)

array([   1,    2, 1000])

In [34]:
type(L1)

list

In [36]:
arr = np.array(L1)

In [37]:
type(arr)

numpy.ndarray

In [38]:
my_mat = [[1,2],[3,4]]

In [39]:
type(my_mat)

list

In [41]:
my_mat = np.array(my_mat)

In [42]:
type(my_mat)

numpy.ndarray

In [48]:
np.arange(30.)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29.])

In [51]:
list(range(0,30,1.5))

TypeError: 'float' object cannot be interpreted as an integer

In [53]:
a = np.arange(1.5, 30., 1.4)

In [55]:
a.shape

(21,)

In [58]:
a= a.reshape(21,1)

In [59]:
a.shape

(21, 1)

In [62]:
a.T.shape

(1, 21)

In [63]:
a+a

array([[ 3. ],
       [ 5.8],
       [ 8.6],
       [11.4],
       [14.2],
       [17. ],
       [19.8],
       [22.6],
       [25.4],
       [28.2],
       [31. ],
       [33.8],
       [36.6],
       [39.4],
       [42.2],
       [45. ],
       [47.8],
       [50.6],
       [53.4],
       [56.2],
       [59. ]])

In [64]:
a = np.arange(1.5, 30., 1.4)

In [65]:
a+a

array([ 3. ,  5.8,  8.6, 11.4, 14.2, 17. , 19.8, 22.6, 25.4, 28.2, 31. ,
       33.8, 36.6, 39.4, 42.2, 45. , 47.8, 50.6, 53.4, 56.2, 59. ])

In [66]:
a*a

array([  2.25,   8.41,  18.49,  32.49,  50.41,  72.25,  98.01, 127.69,
       161.29, 198.81, 240.25, 285.61, 334.89, 388.09, 445.21, 506.25,
       571.21, 640.09, 712.89, 789.61, 870.25])

In [67]:
a/a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.])

In [68]:
a = np.arange(30., 1.4)

In [69]:
a

array([], dtype=float64)

In [73]:
a = np.arange(0,30,2)

In [78]:
ab = a/a

<ipython-input-78-2ff07c3a7a3a>:1: RuntimeWarning: invalid value encountered in true_divide
  ab = a/a


In [81]:
type(ab[0])

numpy.float64

In [85]:
np.nan * 1

nan

In [83]:
np.nan == np.nan

False

In [84]:
np.nan is np.nan

True

In [87]:
sum(ab)

nan

In [90]:
arr = np.arange(1,10,0.1)

In [91]:
arr**2

array([ 1.  ,  1.21,  1.44,  1.69,  1.96,  2.25,  2.56,  2.89,  3.24,
        3.61,  4.  ,  4.41,  4.84,  5.29,  5.76,  6.25,  6.76,  7.29,
        7.84,  8.41,  9.  ,  9.61, 10.24, 10.89, 11.56, 12.25, 12.96,
       13.69, 14.44, 15.21, 16.  , 16.81, 17.64, 18.49, 19.36, 20.25,
       21.16, 22.09, 23.04, 24.01, 25.  , 26.01, 27.04, 28.09, 29.16,
       30.25, 31.36, 32.49, 33.64, 34.81, 36.  , 37.21, 38.44, 39.69,
       40.96, 42.25, 43.56, 44.89, 46.24, 47.61, 49.  , 50.41, 51.84,
       53.29, 54.76, 56.25, 57.76, 59.29, 60.84, 62.41, 64.  , 65.61,
       67.24, 68.89, 70.56, 72.25, 73.96, 75.69, 77.44, 79.21, 81.  ,
       82.81, 84.64, 86.49, 88.36, 90.25, 92.16, 94.09, 96.04, 98.01])

In [92]:
np.sqrt(arr)

array([1.        , 1.04880885, 1.09544512, 1.14017543, 1.18321596,
       1.22474487, 1.26491106, 1.30384048, 1.34164079, 1.37840488,
       1.41421356, 1.44913767, 1.4832397 , 1.51657509, 1.54919334,
       1.58113883, 1.61245155, 1.64316767, 1.67332005, 1.70293864,
       1.73205081, 1.76068169, 1.78885438, 1.81659021, 1.84390889,
       1.87082869, 1.8973666 , 1.92353841, 1.94935887, 1.97484177,
       2.        , 2.02484567, 2.04939015, 2.07364414, 2.0976177 ,
       2.12132034, 2.14476106, 2.16794834, 2.19089023, 2.21359436,
       2.23606798, 2.25831796, 2.28035085, 2.30217289, 2.32379001,
       2.34520788, 2.36643191, 2.38746728, 2.40831892, 2.42899156,
       2.44948974, 2.46981781, 2.48997992, 2.50998008, 2.52982213,
       2.54950976, 2.56904652, 2.58843582, 2.60768096, 2.62678511,
       2.64575131, 2.66458252, 2.68328157, 2.70185122, 2.7202941 ,
       2.73861279, 2.75680975, 2.77488739, 2.79284801, 2.81069386,
       2.82842712, 2.84604989, 2.86356421, 2.88097206, 2.89827

In [93]:
np.exp(arr)

array([2.71828183e+00, 3.00416602e+00, 3.32011692e+00, 3.66929667e+00,
       4.05519997e+00, 4.48168907e+00, 4.95303242e+00, 5.47394739e+00,
       6.04964746e+00, 6.68589444e+00, 7.38905610e+00, 8.16616991e+00,
       9.02501350e+00, 9.97418245e+00, 1.10231764e+01, 1.21824940e+01,
       1.34637380e+01, 1.48797317e+01, 1.64446468e+01, 1.81741454e+01,
       2.00855369e+01, 2.21979513e+01, 2.45325302e+01, 2.71126389e+01,
       2.99641000e+01, 3.31154520e+01, 3.65982344e+01, 4.04473044e+01,
       4.47011845e+01, 4.94024491e+01, 5.45981500e+01, 6.03402876e+01,
       6.66863310e+01, 7.36997937e+01, 8.14508687e+01, 9.00171313e+01,
       9.94843156e+01, 1.09947172e+02, 1.21510418e+02, 1.34289780e+02,
       1.48413159e+02, 1.64021907e+02, 1.81272242e+02, 2.00336810e+02,
       2.21406416e+02, 2.44691932e+02, 2.70426407e+02, 2.98867401e+02,
       3.30299560e+02, 3.65037468e+02, 4.03428793e+02, 4.45857770e+02,
       4.92749041e+02, 5.44571910e+02, 6.01845038e+02, 6.65141633e+02,
      

In [95]:
np.max(arr)

9.900000000000007

In [96]:
np.sin(arr)

array([ 0.84147098,  0.89120736,  0.93203909,  0.96355819,  0.98544973,
        0.99749499,  0.9995736 ,  0.99166481,  0.97384763,  0.94630009,
        0.90929743,  0.86320937,  0.8084964 ,  0.74570521,  0.67546318,
        0.59847214,  0.51550137,  0.42737988,  0.33498815,  0.23924933,
        0.14112001,  0.04158066, -0.05837414, -0.15774569, -0.2555411 ,
       -0.35078323, -0.44252044, -0.52983614, -0.61185789, -0.68776616,
       -0.7568025 , -0.81827711, -0.87157577, -0.91616594, -0.95160207,
       -0.97753012, -0.993691  , -0.99992326, -0.99616461, -0.98245261,
       -0.95892427, -0.92581468, -0.88345466, -0.83226744, -0.77276449,
       -0.70554033, -0.63126664, -0.55068554, -0.46460218, -0.37387666,
       -0.2794155 , -0.1821625 , -0.0830894 ,  0.0168139 ,  0.1165492 ,
        0.21511999,  0.31154136,  0.40484992,  0.49411335,  0.57843976,
        0.6569866 ,  0.72896904,  0.79366786,  0.85043662,  0.8987081 ,
        0.93799998,  0.96791967,  0.98816823,  0.99854335,  0.99

In [97]:
arr.dtype

dtype('float64')

In [101]:
np.array(range(10), dtype=np.float64).dtype

dtype('float64')

In [100]:
np.array(range(10)).dtype

dtype('int32')

In [106]:
np.array(range(10), dtype=complex)

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

# Nan

In [186]:
a= None

In [187]:
type(a)

NoneType

In [193]:
np.array([1,2,None, 50])

array([1, 2, None, 50], dtype=object)

In [200]:
np.arange(1e6, dtype=np.int32)

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [203]:
%timeit np.arange(1e6, dtype='object').sum()

71.6 ms ± 2.66 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [204]:
%timeit np.arange(1e6, dtype=np.int32).sum()

2.69 ms ± 52.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Making Numpy array

In [2]:
import numpy as np

In [207]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [210]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.empty((3,3))

array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 6.166e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

In [4]:
x = np.array([[1,2,],[3,4]], dtype=complex)

In [5]:
x

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [6]:
np.zeros_like(x)

array([[0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j]])

In [8]:
np.empty_like(x)

array([[0.00000000e+000+0.00000000e+000j,
        0.00000000e+000+0.00000000e+000j],
       [0.00000000e+000+6.16593926e-321j,
        8.48798316e-313+8.70018274e-313j]])

In [51]:
x= np.ones(4)
y = np.ones(4)*5

In [36]:
np.vstack((x,y))

array([[1., 1., 1., 1.],
       [5., 5., 5., 5.]])

In [37]:
np.hstack((x,y))

array([1., 1., 1., 1., 5., 5., 5., 5.])

In [56]:
np.concatenate((x,y), axis=0)

array([[1., 1., 1., 1.],
       [5., 5., 5., 5.]])

In [39]:
x.shape

(4,)

In [52]:
x = x.reshape(1,4)

In [53]:
y = y.reshape(1,4)

In [54]:
x.shape

(1, 4)

In [61]:
np.linspace(0,100,500)

array([  0.        ,   0.2004008 ,   0.4008016 ,   0.6012024 ,
         0.80160321,   1.00200401,   1.20240481,   1.40280561,
         1.60320641,   1.80360721,   2.00400802,   2.20440882,
         2.40480962,   2.60521042,   2.80561122,   3.00601202,
         3.20641283,   3.40681363,   3.60721443,   3.80761523,
         4.00801603,   4.20841683,   4.40881764,   4.60921844,
         4.80961924,   5.01002004,   5.21042084,   5.41082164,
         5.61122244,   5.81162325,   6.01202405,   6.21242485,
         6.41282565,   6.61322645,   6.81362725,   7.01402806,
         7.21442886,   7.41482966,   7.61523046,   7.81563126,
         8.01603206,   8.21643287,   8.41683367,   8.61723447,
         8.81763527,   9.01803607,   9.21843687,   9.41883768,
         9.61923848,   9.81963928,  10.02004008,  10.22044088,
        10.42084168,  10.62124248,  10.82164329,  11.02204409,
        11.22244489,  11.42284569,  11.62324649,  11.82364729,
        12.0240481 ,  12.2244489 ,  12.4248497 ,  12.62

# Index

In [77]:
arr = np.array([1,2,3,4])

In [78]:
arr

array([1, 2, 3, 4])

In [79]:
arr[-1]

4

In [80]:
arr[[True, False, True, True]]

array([1, 3, 4])

In [81]:
arr != 2

array([ True, False,  True,  True])

In [82]:
arr[arr != 2]

array([1, 3, 4])

In [84]:
arr[arr<=2]

array([1, 2])

In [85]:
arr = np.linspace(1,200)

In [89]:
arr[arr<50]

array([ 1.        ,  5.06122449,  9.12244898, 13.18367347, 17.24489796,
       21.30612245, 25.36734694, 29.42857143, 33.48979592, 37.55102041,
       41.6122449 , 45.67346939, 49.73469388])

In [88]:
arr

array([  1.        ,   5.06122449,   9.12244898,  13.18367347,
        17.24489796,  21.30612245,  25.36734694,  29.42857143,
        33.48979592,  37.55102041,  41.6122449 ,  45.67346939,
        49.73469388,  53.79591837,  57.85714286,  61.91836735,
        65.97959184,  70.04081633,  74.10204082,  78.16326531,
        82.2244898 ,  86.28571429,  90.34693878,  94.40816327,
        98.46938776, 102.53061224, 106.59183673, 110.65306122,
       114.71428571, 118.7755102 , 122.83673469, 126.89795918,
       130.95918367, 135.02040816, 139.08163265, 143.14285714,
       147.20408163, 151.26530612, 155.32653061, 159.3877551 ,
       163.44897959, 167.51020408, 171.57142857, 175.63265306,
       179.69387755, 183.75510204, 187.81632653, 191.87755102,
       195.93877551, 200.        ])

In [99]:
np.random.randint(2,100,100)

array([31, 36, 93, 28, 28,  6, 65, 81, 72,  4, 31, 32,  5, 90,  7,  9, 88,
       91, 97, 69, 46, 31, 54, 39, 48, 82, 22, 43, 65, 59, 60, 86, 16, 20,
       62, 94,  6, 13, 99, 82, 91, 59, 69,  6, 73, 16,  7, 27, 92,  3, 43,
       55, 44, 10, 83, 55,  2, 22, 87, 95, 60, 32,  7, 46, 14, 80, 16, 26,
       20, 69, 41, 62, 11, 77, 93, 20, 47, 42, 39, 50, 24, 18, 20, 63, 68,
       50, 94, 70, 91, 26, 58, 27, 70, 16,  5, 71, 58, 44, 15, 14])

In [100]:
import math

In [101]:
math.sin([0,1.4])

TypeError: must be real number, not list

In [102]:
vsin = np.vectorize(math.sin)

In [103]:
vsin([0,1.4])

array([0.        , 0.98544973])

In [105]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [110]:
np.arange(100).reshape(20,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

# Logical Comparison

In [141]:
v = np.array([1,2,3])
w = np.array([1,2,4])

In [142]:
v == w

array([ True,  True, False])

In [135]:
if ((v==w).any()):
    print("They are equal")
else:
    print("They are not equal")

They are equal


In [143]:
(v == w) & (v == w)

array([ True,  True, False])

In [144]:
np.logical_and(v == w, v == w)

array([ True,  True, False])

In [147]:
arr = np.random.rand(100,100)

In [152]:
np.savetxt("out.txt", arr)

In [155]:
np.loadtxt("out.txt")

array([[0.11948313, 0.91022723, 0.25086472, ..., 0.26489687, 0.84032701,
        0.52142903],
       [0.98619511, 0.29069497, 0.1013194 , ..., 0.4839556 , 0.53356839,
        0.56048346],
       [0.21491772, 0.30082532, 0.23040455, ..., 0.99104667, 0.93824993,
        0.67311306],
       ...,
       [0.42265135, 0.47607619, 0.14554355, ..., 0.43793888, 0.10813268,
        0.09853369],
       [0.13091192, 0.3156468 , 0.63470475, ..., 0.57313239, 0.90604536,
        0.49259936],
       [0.4410411 , 0.50158932, 0.51293621, ..., 0.40450856, 0.85374927,
        0.09760165]])

In [ ]:
np.save

In [150]:
import os

In [151]:
os.getcwd()

'C:\\Users\\Majid\\Desktop'